### ISSUE TITLE
what this line represent?

### ISSUE THREAD

**Issue by mayankpathaklumiq** [shabie/docformer#10]
output = docformer(v_bar, t_bar, v_bar_s, t_bar_s)  # shape (1, 512, 768)

**Comment by shabie** [comment]
This represents the output of the docformer encoder. Weights are randomly initialized so if you wanted to train it, you'd have to put a head on top of it.

**Comment by uakarsh** [comment]
@mayankpathaklumiq This implementation has been done, with the variables name, similar to that of the paper, so in order to fully grasp it, maybe you just need to keep the code and the paper, side by side, and everything would be clear, since this is what we did
