### ISSUE TITLE
not able to import docformer

### ISSUE THREAD

**Issue by mayankpathaklumiq** [shabie/docformer#11]
I have tried to import docformer by using pip and setup install but did not able to import docformer in ubuntu

**Comment by shabie** [comment]
May be if you can provide the error stack trace, I'd be able to better say what's the reason.

**Comment by shabie** [comment]
May be pull it again and try it. Cuz I fixed a problem with that earlier today.

**Comment by uakarsh** [comment]
@mayankpathaklumiq Maybe, now are you able to import it? If yes, maybe we can close this issue :)
