### ISSUE TITLE
Not able to import docformer

### ISSUE THREAD

**Issue by rlrahulkanojia** [shabie/docformer#17]
After following steps, not able to import to docformer but able to import transformer.

**Comment by uakarsh** [comment]
Can you share the link to your code, if you don't mind? Maybe, you just need to clone it, by using git clone and then import sys to append the path, and the rest all is assured. The code looks something like this:

`!git clone https://github.com/shabie/docformer.git
import sys
sys.path.extend(['docformer/'])
sys.path.extend(['docformer/src/docformer/'])`

I hope, this helps :)

**Comment by rlrahulkanojia** [comment]
It did. Thanks
