### ISSUE TITLE
import error after installing via pip and via command python setup.py install

### ISSUE THREAD

**Issue by mayankpathaklumiq** [shabie/docformer#18]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-83f334e6dba0> in <module>()
----> 1 from docformer import modeling, dataset

ModuleNotFoundError: No module named 'docformer'

**Comment by uakarsh** [comment]
Can you visit this link, and see if it helps?

https://github.com/shabie/docformer/issues/17

**Comment by uakarsh** [comment]
Were you able to solve it?
