### ISSUE TITLE
There is no SEP token appended

### ISSUE THREAD

**Issue by shabie** [shabie/docformer#2]
You have a [SEP] or an equivalent token at the end which I think is not what the authors used:

https://github.com/shabie/docformer/blob/ae1ce38250d9e6ea2f9589fc11b43097045b2488/src/docformer/dataset.py#L260-L261

See the first paragraph of the sub-section "Language Features" in the section 3.1

**Comment by uakarsh** [comment]
You can check it now, I have updated it, and for the bounding boxes as well, I removed the [1000,1000,1000,1000]
