### ISSUE TITLE
Do you have a plan for pre-trained model and inference code?

### ISSUE THREAD

**Issue by yellowjs0304** [shabie/docformer#25]
HI, Thank you for sharing nice work.

I'm new in Document Understanding, I wanna check the inference on FUNSD dataset. 
Could you share any pre-trained models, and inference code?

:) i'm waiting your reply. thank you.

**Comment by uakarsh** [comment]
For the training part, here is the link, which might help you, https://github.com/shabie/docformer/issues/23

As for the model, we have to wait for some time, as the dataset used by the authors is yet unknown (based on a sampling of the different classes and so on), but I guess the link above might help you, give an idea about the training procedure. I would surely add the code for training shortly.

Hope it helps, and do let us know if there are more queries.

Regards,
Akarsh

**Comment by yellowjs0304** [comment]
Thank you for fast reply. I understand what you told. 
But, what i really wanted is only the inference, because i don't have enough resources for training 😥
I would appreciate it if you could consider a method for this part as well.

Sincerely.
