### ISSUE TITLE
checkpoint of docformer

### ISSUE THREAD

**Issue by macheng6** [shabie/docformer#28]
I wonder if you can provide the checkpoint of docformer.  It's a difficult thing for me to train it from scratch. Thank you.

**Comment by uakarsh** [comment]
Hi there,

We are trying our best from our side, and as soon as we get to the checkpoint, we would surely share it.

Regards,

**Comment by macheng6** [comment]
> Thank you.

**Comment by WeihongM** [comment]
Any updates? Does the existing code not reproduce the results of the paper?
Thanks for your reply.
@uakarsh @shabie
