### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by kmr2017** [shabie/docformer#31]
Hi 
I ran the code, it is giving me final output that is too weird irrespective of changing the image.  I am attaching it. Can you explain what it is? 

![image](https://user-images.githubusercontent.com/92592293/166959418-8d2a8e2b-8dd9-40cd-a842-7c6a050218b7.png)

Thanks

**Comment by uakarsh** [comment]
Sorry for the delay, but can do let me know, from which layer did you extract the output?

Regards,

**Comment by kmr2017** [comment]
Hi @uakarsh 

Thanks for your response. 

I tried below code

fp = "img.jpeg"

tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")
encoding = dataset.create_features(fp, tokenizer, add_batch_dim=True)

feature_extractor = modeling.ExtractFeatures(config)
docformer = modeling.DocFormerEncoder(config)
v_bar, t_bar, v_bar_s, t_bar_s = feature_extractor(encoding)
output = docformer(v_bar, t_bar, v_bar_s, t_bar_s)  # shape (1, 512, 768)




then I visualized the output.

**Comment by uakarsh** [comment]
HI,

Actually, we know that the output is (512, 768), now, this output results from the attention of three different entities:
1. Image feature of (512, 768)
2. Language Feature of (512, 768)
3. Spatial Dimension of (512, 768)

Now, when we perform any downstream task, we have an encoded version of these three modalities, so the diagram (which you have plotted) would be helpful for the model to know, which encoding to attend to when performing the downstream task. 

The same can be seen in Pg No. 15, Figure 11. B of [DocFormer Paper](https://arxiv.org/pdf/2106.11539.pdf). Hope it helps

**Comment by kmr2017** [comment]
Thanks for your info.  How can I do entity level classification like in FUNSD dataset?

**Comment by kmr2017** [comment]
@uakarsh

**Comment by uakarsh** [comment]
I have almost finished the training script for RVL-CDIP (Document Classification), and have started working on FUNSD for token classification. 

You can visit my cloned repo, and in the examples/docformer_pl, you can get the
1. Data visualizing 
2. Dataset making
3. MLM with Pytorch Lightning 
4. Document Classification with DocFormer (would be uploaded soon)
 And next would be NER with FUNSD. 

Would update you soon!!

**Comment by BakingBrains** [comment]
@uakarsh Hello,

Any update on  NER with FUNSD using docformer?
