### ISSUE TITLE
DocFormer for Token Classification.

### ISSUE THREAD

**Issue by Akhilesh64** [shabie/docformer#39]
Hi,
First of all great work. I wanted to ask if DocFormer can be used for token classification like LayoutLM series models of Microsoft Research which support tasks like Token Classification, Document Image Classification and Visual Question-Answering and if it does how we can adapt the model to the task of token classification.

**Comment by uakarsh** [comment]
HI there,

This was a question, which has been asked a few times. Currently, I am planning to implement DocFormer for the purpose of Token Classification. The changes won't be much, except for the function `create_features`, and `get_tokens_with_boxes` in the `dataset.py` file.

I would shortly release it as well, and thanks for your kind words!!

Regards,
Akarsh

**Comment by Akhilesh64** [comment]
Sure thanks a lot.

**Comment by uakarsh** [comment]
Hi @Akhilesh64, you can find the code of DocFormer for Token Classification [here](https://github.com/uakarsh/docformer/tree/master/examples/docformer_pl/token_cls)

Regards,
